name: CI Pipeline

on: 
  push:
  workflow_dispatch:


jobs:
  ci:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./source

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run Linter
        run: npm run lint
      - name: Check Formatting
        run: npm run prettier:check 
      - name: Unit Tests
        run: npm run test

      - name: HTML Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: source/
          css: false
          blacklist: |
            node_modules
            docs
      
      - name: CSS Validator
        run: npx stylelint "**/*.css" --config config/.stylelintrc.js
