name: CI Pipeline

on:
  push:
    branches:
      - test-pipeline
jobs: 
  checks: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4 # using version 4 of Actions
      - name: Install Dependencies
        run: npm install
      - name: Linting
        run: npm run lint
        working-directory: ./source
      - name: Formatting
        run: npm run format
        working-directory: ./source
      - name: Run All Unit Tests # uses jest to test everything in the './source/tests/' directory
        run: npx jest source/tests/ # alternatively use 'run: npm test' if the 'package.json' is configured
      - name: Doc Gen
        run: npm run docs
        working-directory: ./source
