name: CI Pipeline

on: [push]
jobs: 
  checks: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4 # using version 4 of Actions
      - name: Install Dependencies
        run: npm install
        working-directory: ./source
      - name: Linting
        run: npm run lint
        working-directory: ./source
      - name: Formatting
        run: npm run format
        working-directory: ./source
      - name: Doc Gen
        run: npm run docs
        working-directory: ./source
