name: CI Pipeline

on: 
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./source

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run Linter
        run: npm run lint
      - name: Check Formatting
        run: npm run prettier:check 
      - name: Doc Gen
        run: npm run docs
